# Generated by Django 2.0 on 2018-01-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sighting',
            options={'ordering': ['-sighted_on'], 'verbose_name': 'Sighting & Encounter', 'verbose_name_plural': 'Sightings & Encounters'},
        ),
    ]
